version: "1"
services:
  - type: web
    name: fairgig-auth
    runtime: python
    repo: https://github.com/hassan-jamshaid10/fairgig-backend.git
    plan: free
    region: oregon
    buildCommand: pip install uv && uv sync --frozen && uv cache prune --ci
    startCommand: uv run uvicorn services.auth.app:app --host 0.0.0.0 --port $PORT
    autoDeployTrigger: commit
    envVars:
    - key: ENV
      value: prod
    - key: SUPABASE_DB_URL
      sync: false
    - key: SECRET_KEY
      sync: false

  - type: web
    name: fairgig-earnings
    runtime: python
    repo: https://github.com/hassan-jamshaid10/fairgig-backend.git
    plan: free
    region: oregon
    buildCommand: pip install uv && uv sync --frozen && uv cache prune --ci
    startCommand: uv run uvicorn services.earnings.app:app --host 0.0.0.0 --port $PORT
    autoDeployTrigger: commit
    envVars:
    - key: ENV
      value: prod
    - key: SUPABASE_DB_URL
      sync: false
    - key: SECRET_KEY
      sync: false

  - type: web
    name: fairgig-grievance
    runtime: python
    repo: https://github.com/hassan-jamshaid10/fairgig-backend.git
    plan: free
    region: oregon
    buildCommand: pip install uv && uv sync --frozen && uv cache prune --ci
    startCommand: uv run uvicorn services.grievance.app:app --host 0.0.0.0 --port $PORT
    autoDeployTrigger: commit
    envVars:
    - key: ENV
      value: prod
    - key: SUPABASE_DB_URL
      sync: false
    - key: SECRET_KEY
      sync: false

  - type: web
    name: fairgig-grievance-node
    runtime: node
    repo: https://github.com/hassan-jamshaid10/fairgig-backend.git
    rootDir: services-node/grievance-service
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
    - key: ENV
      value: prod
    - key: NODE_ENV
      value: production
    - key: SUPABASE_DB_URL
      sync: false
    - key: DATABASE_URL
      sync: false
    - key: AUTH_SERVICE_URL
      sync: false

  - type: web
    name: fairgig-analytics-node
    runtime: node
    repo: https://github.com/hassan-jamshaid10/fairgig-backend.git
    rootDir: services-node/analytics-service
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      sync: false

  - type: web
    name: fairgig-certificate-node
    runtime: node
    repo: https://github.com/hassan-jamshaid10/fairgig-backend.git
    rootDir: services-node/certificate-service
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      sync: false